### ISSUE TITLE
Add column: Posts created

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#974] opened 2017-11-27 12:29 UTC
Number of posts created

**Comment by davidmosterd** [comment] 2017-12-05 15:48
@tobiasschutter Needs elaboration on which list screen, which post type if this has AJAX toggle that specifies more info or that it's a setting which (different) post-types should be displayed in the count.

**Comment by davidmosterd** [comment] 2017-12-06 15:14
Is duplicate of post count column.

**Closed as completed by davidmosterd** 2017-12-06 15:14 UTC
Labels: Type: Improvement, Status: Needs Feedback
