### ISSUE TITLE
V3 to v4 issue is till not fixed

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#1001] opened 2017-12-20 16:18 UTC
Related topic on forum:
https://www.admincolumns.com/forums/topic/500-error-on-pro-activation/

This problem still occurs when deploying a site from v3 to v4 with GIT.

**Comment by davidmosterd** [comment] 2018-01-08 13:46
I think it's not worth the while to fix this.

The issue is legit: we only check the basename now and lowercase it, assuming at least the folder structure went along. This seems to be the case almost always.

However, in some cases, an additional check might help to see if the foldername e.g. filtering is written with lower case. This would require a 3th check on every filename (we already do a 2nd for the basename).

If I have to weigh in the benefits I'd say: this only affects people who have not updated over 9 months ago AND use Git or something to update their code vs. the rest of the people. This is probably by now such a small amount of users. Also, since we have adopted a more 'mature' coding standard this is a problem that won't be repeated and can be considered legacy.

It's never fun to say: won't fix, but I think it's legit in this case as it only applies to a handful of people still on a 9 months old version AND use Git.

**Closed as completed by davidmosterd** 2018-01-08 13:46 UTC
Labels: Type: Bug
