### ISSUE TITLE
Author column on Comments overview sorting is not working

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns-issues#430] opened 2016-03-15 13:55 UTC
Both sorting ascending as descending on author columns is not working (no results found)

Same for column 'In Response to'

**Comment by tobiasschutter** [comment] 2016-03-25 13:14
Could not reproduce anymore. Maybe fixed with another issue. Closed for now.

**Closed as completed by tobiasschutter** 2016-03-25 13:14 UTC
Labels: Type: Bug
