### ISSUE TITLE
Sorting doesn't work for WC Order column Product (type SKU)

### ISSUE THREAD

**Issue by tobiasschutter** [codepress/admin-columns-issues#503] opened 2016-05-02 07:46 UTC

**Comment by DGStefan** [comment] 2016-05-03 09:07
Cannot reproduce this ticket.
Tested it with all display formats of the CPAC_WC_Column_Post_Product column

**Comment by DGStefan** [comment] 2017-04-12 14:33
Fixed in Admin Column 4.0

**Closed as completed by DGStefan** 2017-04-12 14:33 UTC
Labels: Type: Bug, Status: Needs Feedback
